### ISSUE TITLE
UART emulation question

### ISSUE THREAD

**Issue by leochen66** [xpack-dev-tools/qemu-arm-xpack#10]
Hi there,
Sorry this is not an actual issue, but a personal question.
I'm a vey beginner of QEMU and mcu programing.
I followed your guide(the blink tutorial) to test qemu-arm-xpack by Eclipse plug-in.
Then i tried to practice other interfaces like uart on Eclipse.
There is a problem that is there any way i can emulation the serial port connected to my host device.
Thanks

**Comment by ilg-ul** [comment]
https://xpack.github.io/qemu-arm/#compatibility--peripherals

For support and further questions, please use the project forum.
