### ISSUE TITLE
NVIC: Bad read offset 0xd94

### ISSUE THREAD

**Issue by nian-hua** [xpack-dev-tools/qemu-arm-xpack#11]
Hi there,

I use QEMU-ARM-XPACK to simulate STM32 firmware, It's working. 

But when I reading the memory protect unit(MPU) value, Error info :

![image](https://user-images.githubusercontent.com/41846038/114517757-3a670680-9c71-11eb-983b-ddd5f52e5ce5.png)

![image](https://user-images.githubusercontent.com/41846038/114517654-20c5bf00-9c71-11eb-98ee-d0ac72e082d7.png)

Thanks.

**Comment by ilg-ul** [comment]
https://xpack.github.io/qemu-arm/#compatibility--peripherals
